- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
  tasks: 
    - include: tasks/node.yml
    - include: tasks/zsh.yml
